### ISSUE TITLE
Capturing stdout from porter hangs around 1k lines

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter-vscode#13]
When porter schema returns more than 1,000 lines (estimated), the extension never is able to return from collecting the schema. If I hard code the schema into the extension it works fine, however.

**Comment by carolynvs** [comment]
Here is my current workaround:

1. Download the patch (named .txt so github would let me attach it)
1. git apply autocomplete-workaround.patch.txt
2. porter schema | pbcopy
3. Copy paste the clipboard into src/porter/porter.ts at line 42 replacing the TODO
4. Hit F5

[autocomplete-workaround.patch.txt](https://github.com/deislabs/porter-vscode/files/3662912/autocomplete-workaround.patch.txt)

**Comment by carolynvs** [comment]
@itowlson Heads up, this bug is affecting our demo for Oct 22nd.

**Comment by itowlson** [comment]
Ugh, no repro on Windows.  Not sure what Mac or Linux does differently...

**Comment by itowlson** [comment]
Fixed via #14.
