### ISSUE TITLE
JSON Schema issue with custom actions and images

### ISSUE THREAD

**Issue by squillace** [deislabs/porter-vscode#18]
using https://github.com/jeremyrickard/do-porter:

porter v0.20.0-beta.1 (bd40408)

VS Code porter extension: 0.0.1

![image](https://user-images.githubusercontent.com/1422718/67163348-d2fe1e00-f33b-11e9-88d9-36a5b29028c1.png)

**Comment by squillace** [comment]
@carolynvs I'm still showing that the `images` section still throws validation errors, though the customActions is in fact fixed. Do you see what I see?

![image (6)](https://user-images.githubusercontent.com/1422718/68091666-45005800-fe50-11e9-9b00-9b62678b6486.png)
d in 20.2.

**Comment by jeremyrickard** [comment]
Taking a look now ☝️

**Comment by carolynvs** [comment]
This is fixed in the latest version of Porter.
